### PR TITLE
fix: sail update

### LINKED ISSUE #7: sail update doesn't work
and I'm on it :)

### PR DESCRIPTION
**Pull request by yesnault**
Close #7

Signed-off-by: Yvonnick Esnault <yvonnick.esnault@ovh.net>

### CODE REVIEW

File: update/snapshot.go [hunk 1]
```diff
@@ -0,0 +1,19 @@
...
+
+// used by CI to inject url for downloading with tatcli update.
+// value of urlUpdate injected at build time
+// full URL update is constructed with architecture var :
+// urlUpdate + "tatcli-" + architecture, tatcli is the binary
+var urlUpdateSnapshot string
+
+var cmdUpdateSnapshot = &cobra.Command{
+	Use:     "snapshot",
+	Short:   "Update tatcli to latest snapshot version: tatcli update snapshot",
```
Comment (yadutaf) [inline update/snapshot.go]: s/tatcli/sail/g

File: update/update.go [hunk 2]
```diff
@@ -30,38 +23,64 @@ func init() {
...
+	fmt.Printf("Getting latest release from : %s ...\n", url)
 	defer resp.Body.Close()
 	err = update.Apply(resp.Body, update.Options{})
 	if err != nil {
-		internal.Exit("Error when updating sail\n", err)
+		fmt.Printf("Error when updating sail: %s\n", err.Error())
+		fmt.Printf("Url: %s\n", url)
+		os.Exit(1)
 	}
+	fmt.Println("Updating done.")
```
Comment (yadutaf) [inline update/update.go]: Update done

File: package.sh [hunk 3]
```diff
@@ -6,6 +6,6 @@ for GOOS in darwin linux windows; do
         echo "Building ${architecture}"
         export GOOS=$GOOS
         export GOARCH=$GOARCH
-        go build -ldflags "-X ${PROJECT_PATH}/${PROJECT_NAME}/update.architecture=${architecture} -X ${PROJECT_PATH}/${PROJECT_NAME}/update.urlUpdateRelease=${URL_UPDATE_RELEASE} -X ${PROJECT_PATH}/${PROJECT_NAME}/update.urlUpdateSnapshot=${URL_UPDATE_SNAPSHOT}" -o bin/sail-${architecture}
+        go build -ldflags "-X ${PROJECT_PATH}/${PROJECT_NAME}/update.architecture=${architecture} -X ${PROJECT_PATH}/${PROJECT_NAME}/update.urlUpdateSnapshot=${URL_UPDATE_SNAPSHOT}" -o bin/sail-${architecture}
```
Comment (yadutaf) [inline package.sh]: Isn't is ``update..snapshot.urlUpdateSnapshot`` instead of ``update.urlUpdateSnapshot`` ?

File: update/snapshot.go [hunk 4]
```diff
@@ -0,0 +1,19 @@
+package update
+
+import "github.com/spf13/cobra"
+
+// used by CI to inject url for downloading with tatcli update.
+// value of urlUpdate injected at build time
+// full URL update is constructed with architecture var :
+// urlUpdate + "tatcli-" + architecture, tatcli is the binary
+var urlUpdateSnapshot string
```
Comment (yadutaf) [inline update/snapshot.go]: As there is no Github URL for ``urlUpdateSnapshot``, I'd rather not expose this feature, at least not in the default build to avoid user frustration.

File: update/update.go [hunk 5]
```diff
@@ -30,38 +23,64 @@ func init() {
...
-	Long:    `sail update snapshot`,
-	Aliases: []string{"snap"},
-	Run: func(cmd *cobra.Command, args []string) {
-		doUpdate(urlUpdateSnapshot, architecture)
-	},
+func getURLArtifactFromGithub(architecture string) string {
+	client := github.NewClient(nil)
+	release, resp, err := client.Repositories.GetLatestRelease("runabove", "sail")
+	if err != nil {
+		fmt.Printf("Repositories.GetLatestRelease returned error: %v\n%v", err, resp.Body)
```
Comment (yadutaf) [inline update/update.go]: stderr ?

File: update/update.go [hunk 6]
```diff
@@ -30,38 +23,64 @@ func init() {
...
+
+	if len(release.Assets) > 0 {
+		for _, asset := range release.Assets {
+			if *asset.Name == "sail-"+architecture {
+				return *asset.BrowserDownloadURL
+			}
+		}
+	}
+
+	fmt.Println("Invalid Artifacts on latest release. Please try in few minutes.")
```
Comment (yadutaf) [inline update/update.go]: Try again*

File: update/update.go [hunk 7]
```diff
@@ -30,38 +23,64 @@ func init() {
...
+	fmt.Println("If it's persit, please open an issue on https://github.com/runabove/sail/issues")
```
Comment (yadutaf) [inline update/update.go]: If the problem persists,

File: package.sh (hunk 3 above)
Comment (yesnault) [inline package.sh]: urlUpdateRelease is always github, so no need to set it in package.sh
urlUpdateSnapshot can be set on package.sh

Comment (yesnault) [inline package.sh]: See func https://github.com/runabove/sail/blob/fixSailUpdate/update/update.go#L34

File: update/update.go (hunk 2 above)
Comment (yesnault) [inline update/update.go]: done.

File: update/update.go [hunk 8]
```diff
@@ -30,38 +23,64 @@ func init() {
...
+		fmt.Println("Please download latest release on https://github.com/runabove/sail/releases")
+		os.Exit(1)
+	}
+	url := getURLArtifactFromGithub(architecture)
 	if internal.Verbose {
-		fmt.Fprintf(os.Stderr, "Debug: updating from %s\n", url)
+		fmt.Printf("Url to update sail: %s\n", url)
 	}
-
 	resp, err := http.Get(url)
```
Comment (yadutaf) [inline update/update.go]: Can we add an expectation on the content type ? Or some heuristic testing like running "sail version" on the new version before replacing the current binary ? I've had fun side-effects with HTML binaries in the past :)

File: update/update.go [hunk 9]
```diff
@@ -30,38 +23,64 @@ func init() {
...
+		os.Exit(1)
 	}
+	if resp.StatusCode != 200 {
+		fmt.Printf("Error http code: %d, url called: %s\n", resp.StatusCode, url)
+		os.Exit(1)
+	}
+
+	fmt.Printf("Getting latest release from : %s ...\n", url)
 	defer resp.Body.Close()
 	err = update.Apply(resp.Body, update.Options{})
```
Comment (yadutaf) [inline update/update.go]: Hmm ? Could not find where does "update" come from. Any hint ?

File: package.sh (hunk 3 above)
Comment (yadutaf) [inline package.sh]: The path of the variable, isn't there a typo in ?

File: update/snapshot.go (hunk 4 above)
Comment (yesnault) [inline update/snapshot.go]: this feature is not exposed by binary build from travis.
see https://github.com/runabove/sail/blob/fixSailUpdate/update/update.go#L18
but I can move 
```
func init() {
	if urlUpdateSnapshot != "" {
		Cmd.AddCommand(cmdUpdateSnapshot)
	}
}
```
into snapshot.go

File: package.sh (hunk 3 above)
Comment (yadutaf) [inline package.sh]: Oh, got it. The path did not change as this is the package name, *not* the *file* name.

File: update/snapshot.go (hunk 4 above)
Comment (yesnault) [inline update/snapshot.go]: moved :)

File: update/update.go (hunk 7 above)
Comment (yesnault) [inline update/update.go]: done.

File: update/update.go (hunk 5 above)
Comment (yesnault) [inline update/update.go]: done.

File: update/update.go (hunk 6 above)
Comment (yesnault) [inline update/update.go]: done

File: update/snapshot.go (hunk 1 above)
Comment (yesnault) [inline update/snapshot.go]: done.

**Comment by yadutaf** [comment]
LGTM :+1: Ready to merge when I have your go

File: update/update.go (hunk 9 above)
Comment (yesnault) [inline update/update.go]: hum, I did not understand your comment :-D

File: update/update.go (hunk 8 above)
Comment (yesnault) [inline update/update.go]: Sure, I'll try to do something on that

**Comment by yesnault** [comment]
Do not merge for now

File: update/update.go (hunk 8 above)
Comment (yesnault) [inline update/update.go]: done.

**Comment by yesnault** [comment]
if check content-type is ok for you, you can merge.

**Comment by yesnault** [comment]
see check here : https://github.com/runabove/sail/blob/fixSailUpdate/update/update.go#L79

**Comment by yadutaf** [comment]
It is. That's a safety belt. Thanks.
